"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.hbomax = exports.valentino = exports.cann = exports.bumbleBizz = exports.bumbleBFF = exports.bumbleDate = exports.voting = exports.raceAndPrivilege = exports.quarantine = exports.sneakyLink = exports.exfriend = exports.selfLove = exports.selfReflection = exports.forgiveness = exports.healing = exports.breakup = exports.ownIt = exports.innerCircle = exports.relationship = exports.honestDating = exports.couples = exports.family = exports.main = void 0;
const main_json_1 = __importDefault(require("./mainDeck/main.json"));
const main_vi_json_1 = __importDefault(require("./mainDeck/main_vi.json"));
const family_json_1 = __importDefault(require("./expansion/family.json"));
const couples_json_1 = __importDefault(require("./expansion/couples.json"));
const honestDating_json_1 = __importDefault(require("./expansion/honestDating.json"));
const relationship_json_1 = __importDefault(require("./expansion/relationship.json"));
const innerCircle_json_1 = __importDefault(require("./expansion/innerCircle.json"));
const ownIt_json_1 = __importDefault(require("./expansion/ownIt.json"));
const breakup_json_1 = __importDefault(require("./self/breakup.json"));
const healing_json_1 = __importDefault(require("./self/healing.json"));
const forgiveness_json_1 = __importDefault(require("./self/forgiveness.json"));
const selfReflection_json_1 = __importDefault(require("./self/selfReflection.json"));
const selfLove_json_1 = __importDefault(require("./self/selfLove.json"));
const exfriend_json_1 = __importDefault(require("./online/exfriend.json"));
const sneaky_json_1 = __importDefault(require("./online/sneaky.json"));
const quarantine_json_1 = __importDefault(require("./online/quarantine.json"));
const raceAndPrivilege_json_1 = __importDefault(require("./online/raceAndPrivilege.json"));
const voting_json_1 = __importDefault(require("./online/voting.json"));
const bumbleDate_json_1 = __importDefault(require("./crossover/bumbleDate.json"));
const bumbleBFF_json_1 = __importDefault(require("./crossover/bumbleBFF.json"));
const bumbleBizz_json_1 = __importDefault(require("./crossover/bumbleBizz.json"));
const cann_json_1 = __importDefault(require("./crossover/cann.json"));
const valentino_json_1 = __importDefault(require("./crossover/valentino.json"));
const hboMax_json_1 = __importDefault(require("./crossover/hboMax.json"));
function mergeLocale(base, localeJson) {
    return { ...base, ...localeJson };
}
exports.main = mergeLocale(main_json_1.default, main_vi_json_1.default);
exports.family = family_json_1.default;
exports.couples = couples_json_1.default;
exports.honestDating = honestDating_json_1.default;
exports.relationship = relationship_json_1.default;
exports.innerCircle = innerCircle_json_1.default;
exports.ownIt = ownIt_json_1.default;
exports.breakup = breakup_json_1.default;
exports.healing = healing_json_1.default;
exports.forgiveness = forgiveness_json_1.default;
exports.selfReflection = selfReflection_json_1.default;
exports.selfLove = selfLove_json_1.default;
exports.exfriend = exfriend_json_1.default;
exports.sneakyLink = sneaky_json_1.default;
exports.quarantine = quarantine_json_1.default;
exports.raceAndPrivilege = raceAndPrivilege_json_1.default;
exports.voting = voting_json_1.default;
exports.bumbleDate = bumbleDate_json_1.default;
exports.bumbleBFF = bumbleBFF_json_1.default;
exports.bumbleBizz = bumbleBizz_json_1.default;
exports.cann = cann_json_1.default;
exports.valentino = valentino_json_1.default;
exports.hbomax = hboMax_json_1.default;
